force-app/main/default/objects/FSK_FSL_Starter_Kit__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This Custom Settings object is part of the Starter Kit.
It stores the pack properties and preferences</description>
    <fields>
        <fullName>Actual_Times_on_Gantt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Actual Times on Gantt</label>
        <type>Checkbox</type>
    </fields>
    <label>FSL Starter Kit</label>
</CustomObject>

force-app/main/default/classes/FSK_SettingsPageCtrlTest.cls
/**
 * @author Shani Joffe
 * @Date 30/12/2020
 */

@IsTest
public with sharing class FSK_SettingsPageCtrlTest {

    @IsTest
    public static void testgetSK_SettingsCSFromOrg() {
        
        Test.startTest();   
        FSK_FSL_Starter_Kit__c sk = FSK_FSL_Starter_Kit__c.getOrgDefaults();
        FSK_FSL_Starter_Kit__c skTest = FSK_SettingsPageCtrl.getSK_SettingsCSFromOrg();
        
        System.assertNotEquals(skTest, null);
        skTest.Actual_Times_on_Gantt__c = true;
        FSK_SettingsPageCtrl.saveSkSettings(skTest);   
        FSK_FSL_Starter_Kit__c skTestUpdated = FSK_SettingsPageCtrl.getSK_SettingsCSFromOrg();

        System.assertEquals(skTest.Actual_Times_on_Gantt__c, skTestUpdated.Actual_Times_on_Gantt__c);

        Test.stopTest();

     }
    
}